version: "3"

services:
  Router:
      image: ubuntu
      container_name: router
      tty: true
      cap_add:
        - ALL
      sysctls:
        - net.ipv4.ip_forward=1
      networks:
          net-10.9.0.0:
              ipv4_address: 10.9.0.11
    
  user-dns-club:
    container_name: user-dns-club3
    image: dns-client-club
    tty: true
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.4
         
  client-club:
    container_name: client-club3
    image: client-club
    tty: true
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3

  server-club:
    container_name: server-club3
    image: server-club
    tty: true
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.6

  attacker-club:
      image: attacker-club
      container_name: attacker
      tty: true
      privileged: true
      cap_add:
        - ALL
      sysctls:
        - net.ipv4.ip_forward=1
      networks:
          net-10.9.0.0:
              ipv4_address: 10.9.0.9

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
    driver_opts:
        com.docker.network.bridge.name: lab-interface
