version: "3"

services:
  Router:
      image: cyberclub-user
      container_name: router
      tty: true
      cap_add:
        - ALL
      sysctls:
        - net.ipv4.ip_forward=1
      networks:
          net-10.9.0.0:
              ipv4_address: 10.9.0.11
         
  club-user-1:
    container_name: user1
    image: cyberclub-user
    tty: true
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2

  club-user-2:
    container_name: user2
    image: cyberclub-user
    tty: true
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3

  attacker-club:
      image: cyberclub-user
      container_name: attacker
      tty: true
      cap_add:
        - ALL
      sysctls:
        - net.ipv4.ip_forward=1
      volumes:
        - ./volumes:/volumes
      networks:
          net-10.9.0.0:
              ipv4_address: 10.9.0.9

  

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
